package io.github.rodrigoma.nfse.model.response

import io.github.rodrigoma.nfse.exception.NfseError
import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime

/**
 * An NFS-e as generated by the Sefin Nacional, parsed from the `NFSe` XML.
 *
 * @property accessKey 50-digit access key (`infNFSe/@Id` without the `NFS` prefix).
 * @property number `nNFSe` — assigned by the Sefin, sequential per emitter.
 * @property statusCode `cStat` (`100` generated, `102` judicial decision, `103` avulsa, `107` MEI).
 * @property dpsId `Id` of the DPS embedded in the note.
 * @property netAmount `vLiq`.
 * @property xml The complete `NFSe` XML for the application to keep.
 */
data class Nfse(
    val accessKey: String,
    val number: String,
    val statusCode: String,
    val processedAt: OffsetDateTime?,
    val emitterMunicipality: String?,
    val dpsId: String?,
    val netAmount: BigDecimal?,
    val calculationBase: BigDecimal? = null,
    val appliedRate: BigDecimal? = null,
    val issqnAmount: BigDecimal? = null,
    val xml: String,
)

/**
 * Result of `POST /nfse`.
 *
 * @property alerts `alertas[]` — warnings the Sefin attached to a note it still generated.
 */
data class NfseResult(
    val accessKey: String,
    val nfseNumber: String,
    val processedAt: OffsetDateTime?,
    val dpsId: String,
    val nfse: Nfse,
    /** The signed DPS exactly as sent, for the application to keep. */
    val dpsXml: String,
    val alerts: List<NfseError> = emptyList(),
) {
    val nfseXml: String get() = nfse.xml
}

/**
 * A response of the ADN Parâmetros Municipais service. Every endpoint answers `{ "mensagem": …, <payload>: … }`
 * (`adn-parametrizacao.openapi.json`); [raw] is the whole parsed JSON object and [message] its `mensagem`.
 */
data class MunicipalParameters(
    val municipalityIbge: Int,
    val serviceCode: String? = null,
    val competence: LocalDate? = null,
    val message: String? = null,
    val raw: Map<String, Any?>,
)
