package io.github.rodrigoma.nfse.model.dps

import java.math.BigDecimal
import java.time.LocalDate

/** Reference of a deduction/reduction document (`docDedRed` choice). */
sealed interface DeductionDocumentReference {
    data class NfseKey(
        val accessKey: String,
    ) : DeductionDocumentReference

    data class NfeKey(
        val accessKey: String,
    ) : DeductionDocumentReference

    data class MunicipalNfse(
        val municipalityIbge: Int,
        val number: String,
        val verificationCode: String,
    ) : DeductionDocumentReference

    data class NfNfs(
        val number: String,
        val model: String,
        val series: String,
    ) : DeductionDocumentReference

    data class FiscalDocumentNumber(
        val number: String,
    ) : DeductionDocumentReference

    data class DocumentNumber(
        val number: String,
    ) : DeductionDocumentReference
}

/** `docDedRed`. */
data class DeductionDocument(
    val reference: DeductionDocumentReference,
    val type: DeductionType,
    /** Required when [type] is [DeductionType.OTHER]. */
    val otherDescription: String? = null,
    val issueDate: LocalDate,
    val deductibleAmount: BigDecimal,
    val deductedAmount: BigDecimal,
    val supplier: Person? = null,
)

/** `vDedRed` — one of a percentage, a flat amount or an itemised document list. */
sealed interface Deductions {
    data class Percentage(
        val percentage: BigDecimal,
    ) : Deductions

    data class Amount(
        val amount: BigDecimal,
    ) : Deductions

    data class Documents(
        val documents: List<DeductionDocument>,
    ) : Deductions
}

/** `exigSusp`. */
data class SuspendedEnforceability(
    val type: SuspensionType,
    /** 30 digits, zero-padded by the builder. */
    val processNumber: String,
)

/** Reduction attached to a municipal benefit (`vRedBCBM` | `pRedBCBM`). */
sealed interface BenefitReduction {
    data class Amount(
        val amount: BigDecimal,
    ) : BenefitReduction

    data class Percentage(
        val percentage: BigDecimal,
    ) : BenefitReduction
}

/** `BM`. */
data class MunicipalBenefit(
    /** `nBM` — 14-digit identifier generated by the national system. */
    val number: String,
    val reduction: BenefitReduction? = null,
)

/** `tribMun` (`TCTribMunicipal`). */
data class MunicipalTax(
    val taxation: IssqnTaxation = IssqnTaxation.TAXABLE,
    /** `cPaisResult` — country where the service result happens (exports). */
    val resultCountryIso: String? = null,
    val immunityType: IssqnImmunityType? = null,
    val suspendedEnforceability: SuspendedEnforceability? = null,
    val municipalBenefit: MunicipalBenefit? = null,
    val withholding: IssqnWithholding = IssqnWithholding.NOT_WITHHELD,
    /** `pAliq` — percentage (`2.00` = 2 %), max 5 %; when it must (not) be sent depends on the regime (Anexo I). */
    val rate: BigDecimal? = null,
)

/** `piscofins`. */
data class PisCofins(
    /** `CST` — 2-digit code. */
    val cst: String,
    val calculationBase: BigDecimal? = null,
    val pisRate: BigDecimal? = null,
    val cofinsRate: BigDecimal? = null,
    val pisAmount: BigDecimal? = null,
    val cofinsAmount: BigDecimal? = null,
    val withholding: PisCofinsWithholding? = null,
)

/** `tribFed`. */
data class FederalTax(
    val pisCofins: PisCofins? = null,
    val withheldSocialSecurity: BigDecimal? = null,
    val withheldIncomeTax: BigDecimal? = null,
    val withheldCsll: BigDecimal? = null,
)

/** `totTrib` — approximate total tax burden (Lei 12.741/2012). */
sealed interface TotalTaxes {
    data class Amounts(
        val federal: BigDecimal,
        val state: BigDecimal,
        val municipal: BigDecimal,
    ) : TotalTaxes

    data class Percentages(
        val federal: BigDecimal,
        val state: BigDecimal,
        val municipal: BigDecimal,
    ) : TotalTaxes

    /** `indTotTrib = 0` — no estimate informed. */
    data object NotInformed : TotalTaxes

    /** `pTotTribSN` — the Simples Nacional percentage. */
    data class SimplesNacionalPercentage(
        val percentage: BigDecimal,
    ) : TotalTaxes
}

/** `trib`. */
data class Taxes(
    val municipal: MunicipalTax = MunicipalTax(),
    val federal: FederalTax? = null,
    val total: TotalTaxes = TotalTaxes.NotInformed,
)

/** `valores` (`TCInfoValores`). Money is `BigDecimal`, written with exactly two decimals. */
data class Amounts(
    /** `vServ`. */
    val serviceAmount: BigDecimal,
    /** `vReceb`. */
    val receivedAmount: BigDecimal? = null,
    /** `vDescIncond`. */
    val unconditionalDiscount: BigDecimal? = null,
    /** `vDescCond`. */
    val conditionalDiscount: BigDecimal? = null,
    val deductions: Deductions? = null,
    val taxes: Taxes = Taxes(),
)
